language: r
sudo: false
cache: packages
pandoc_version: 2.7.3

env:
  global:
    - R_PKG="$(basename $TRAVIS_REPO_SLUG)" _R_CHECK_TESTS_NLINES_=0

before_install:
  - "curl -L https://xran.yihui.org/.gitconfig -o ~/.gitconfig"
  - Rscript -e 'if (!require("covr")) install.packages("covr")'

before_script:
  - R CMD INSTALL .
  - Rscript tools/test-packages.R

after_success:
  - Rscript -e 'covr::codecov()'
  - "(curl -L https://xran.yihui.org/r-xran | bash)"
