environment:
  PATH: "%APPDATA%\\TinyTeX\\bin\\win32;%PATH%"

init:
  ps: |
        $ErrorActionPreference = "Stop"
        Invoke-WebRequest http://raw.github.com/krlmlr/r-appveyor/master/scripts/appveyor-tool.ps1 -OutFile "..\appveyor-tool.ps1"
        Import-Module '..\appveyor-tool.ps1'

install:
  ps: Bootstrap

cache:
  - C:\RLibrary

build_script:
  - set PATH=%PATH:C:\MinGW\msys\1.0\bin;=%
  - echo | tools\install-windows.bat
  - Rscript -e "update.packages(ask = FALSE, checkBuilt = TRUE, repos = 'https://cran.rstudio.com')"

test_script:
  - tlmgr --version
  - pdflatex --version
  - xelatex --version
  - Rscript -e "tinytex::tlmgr_install(readLines('tools/pkgs-yihui.txt'))"
  - 7z a TinyTeX.zip %APPDATA%\\TinyTeX
  - travis-tool.sh install_deps
  - travis-tool.sh run_tests
  - R CMD INSTALL .
  - Rscript -e "tinytex::install_tinytex(force = TRUE)"

artifacts:
  - path: TinyTeX.zip
    name: TinyTeX
